//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class HelloView:public drogon::DrTemplate<HelloView>
{
public:
	HelloView(){};
	virtual ~HelloView(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
